version: '3'
services:
  pubsub-emulator:
    image: aongko/pubsub-emulator
    container_name: pubsub_emulator
    ports:
      - "8538:8538"
    volumes:
      - ./data:/data
    command: ["start", "--host-port=0.0.0.0:8538", "--data-dir=/data"]
